<?php

namespace YM\Umi\DataTable;

class umiDataTableWithSearch extends umiDataTableAbstract
{
    public function header()
    {
        return parent::header(); // TODO: Change the autogenerated stub
    }

    public function tableBody()
    {
        //echo 'function of search';
        return parent::tableBody();
    }

    public function footer()
    {
        return parent::footer(); // TODO: Change the autogenerated stub
    }
}