<?php

namespace YM\Umi\DataTable;

class umiDataTable extends umiDataTableAbstract
{
    public function header()
    {
        parent::header(); // TODO: Change the autogenerated stub
    }

    public function tableBody()
    {
        parent::tableBody(); // TODO: Change the autogenerated stub
    }

    public function footer()
    {
        parent::footer(); // TODO: Change the autogenerated stub
    }
}